language: python
python:
  - "3.8"
cache: pip

before_install:
  - pip install behave
  - rvm install 2.3
  - rvm use 2.3
  - gem install hiptest-publisher

install: pip install -r requirements.txt
         pip install selenium
         pip install coveralls
addons:
  sonarcloud:
    organization: "damianlacomba_ahorcado2020" 
    token:
      secure: b1da882ae7c1605ef1d8d81221a2363fc06b48c1
 
script: behave --junit --junit-directory results 

after_success: 
 - coveralls

deploy:
  provider: heroku
  app: agiles20-ahorcado
  api_key: d2dc6c55-2642-4291-a369-ee0a27e66ff1
