build: trusty
language: python
python:
  - "3.8"
cache: pip

install: pip install -r requirements.txt
         pip install coveralls
         pip install behave
         pip install selenium
         pip install webdriver-manager
        
addons:
  sonarcloud:
    organization: "damianlacomba_ahorcado2020" 
    token:
      secure: b1da882ae7c1605ef1d8d81221a2363fc06b48c1

before_script:
        - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}\Users\Damian\Downloads\chromedriver_win32\chromedriver.exe"
        - wget https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_win32.zip
        - unzip chromedriver_win32.zip -d /home/travis/virtualenv/python3.8.0/bin/

 
script: behave --format json -o results/results.json 

after_success: 
 - coveralls

deploy:
  provider: heroku
  app: agiles20-ahorcado
  api_key: d2dc6c55-2642-4291-a369-ee0a27e66ff1
