language: python
python:
  - "3.8"
cache: pip
install: "pip install -r requirements.txt"
script: python -m unittest Test_ahorcado
deploy:
  provider: heroku
  api_key:
    secure: 8f0c7fd4-4121-4b08-acec-ab81d7d46527
  app: agiles20-ahorcado
  on:
    repo: damianlacomba/ahorcado2020