language: python
python:
  - "3.8"
cache: pip
install: "pip install -r requirements.txt"
           "pip install coverage"
           "pip install coveralls"

addons:
  sonarcloud:
    organization: "damianlacomba_ahorcado2020" 
    token:
      secure: b1da882ae7c1605ef1d8d81221a2363fc06b48c1

script: 
        coverage run -m unittest discover -s . -p 'Test_ahorcado.py'
      
deploy:
  provider: heroku
  app: agiles20-ahorcado
  api_key: d2dc6c55-2642-4291-a369-ee0a27e66ff1

  after_success:
  coveralls
